# Generated by Django 4.2.30 on 2026-05-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'ผู้ซื้อ'), ('seller', 'ผู้ขาย')], default='buyer', help_text='User role: buyer or seller', max_length=10),
        ),
    ]
