# Generated by Django 4.2.30 on 2026-05-06 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, help_text='Auto-generated unique order number', max_length=20, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all order items', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending — awaiting payment'), ('PAID', 'Paid — payment verified'), ('SHIPPED', 'Shipped — delivery slip printed'), ('COMPLETED', 'Completed — delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(help_text='User who placed this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sale_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_received', models.DecimalField(decimal_places=2, help_text='Amount buyer paid', max_digits=12)),
                ('payment_slip', models.ImageField(blank=True, help_text='Transfer receipt / payment proof image', null=True, upload_to='payment_slips/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending verification'), ('VERIFIED', 'Verified by seller'), ('REJECTED', 'Rejected by seller')], default='PENDING', max_length=10)),
                ('payment_method', models.CharField(default='bank_transfer', help_text='e.g. bank_transfer, promptpay', max_length=50)),
                ('note', models.TextField(blank=True, default='', help_text="Seller's note on verification")),
                ('paid_at', models.DateTimeField(blank=True, help_text='When buyer made the payment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.saleorder')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price at time of purchase (snapshot)', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='quantity × unit_price', max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.saleorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='DeliverySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_number', models.CharField(editable=False, help_text='Unique slip number for package label', max_length=20, unique=True)),
                ('tracking_number', models.CharField(blank=True, default='', help_text='Shipping carrier tracking number', max_length=100)),
                ('stock_deducted', models.BooleanField(default=False, help_text='True after Celery task deducted stock')),
                ('printed_at', models.DateTimeField(blank=True, help_text='When the slip was printed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_slip', to='orders.saleorder')),
            ],
            options={
                'db_table': 'delivery_slips',
            },
        ),
    ]
