# Generated by Django 4.2.30 on 2026-05-06 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW', 'Viewed product'), ('ADD_CART', 'Added to cart'), ('REMOVE_CART', 'Removed from cart'), ('PURCHASE', 'Purchased')], max_length=15)),
                ('metadata', models.JSONField(blank=True, help_text='Extra data: e.g. cart quantity, time spent viewing', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_behaviors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action'], name='user_behavi_user_id_9de40f_idx'), models.Index(fields=['product', 'action'], name='user_behavi_product_182305_idx')],
            },
        ),
    ]
